trigger:
- master

pool:
  vmImage: windows-latest

variables:
- group: sql-ded-restore

steps:
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: mandscon
    AuthenticationType: 'server'
    ServerName: $(serverName).sql.azuresynapse.net
    DatabaseName: $(sourceDatabaseName)
    SqlUsername: '$(srcSqlUser)'
    SqlPassword: '$(srcSqlPwd)'
    deployType: 'DacpacTask'
    DeploymentAction: Extract
    DacpacFile: '$(sourceDatabaseName).dacpac'
    # AdditionalArguments: '/Variables:ADLSLocation=abfss://datalake@$(datalakeAccountName).dfs.core.windows.net /Variables:ADLSCredentialKey=$(datalakeKey)'
  displayName: 'Extract DACPAC From Source synapse dedicated sql pool'
  

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: mandscon
    AuthenticationType: 'server'
    ServerName: $(serverName).sql.azuresynapse.net
    DatabaseName: $(sinkDatabaseName)
    SqlUsername: '$(sinkSqlUser)'
    SqlPassword: '$(sinkSqlPwd)'
    deployType: 'DacpacTask'
    DacpacFile: 'GeneratedOutputFiles/$(sourceDatabaseName).dacpac'
    # AdditionalArguments: '/Variables:ADLSLocation=abfss://datalake@$(datalakeAccountName).dfs.core.windows.net /Variables:ADLSCredentialKey=$(datalakeKey)'
  displayName: 'Deploy DACPAC to synapse dedicated sql pool'
